commandSender: "Autoban"
servergroups:
   default:
    - lobby

counters:
   insult:
      max: 4
      ttl: 60
      action: ban
      reason: Insult
   spam:
      max: 6
      ttl: 30
      action: tempban
      reason: Spam

actions:
   ban:
      kick: true
      playerserver:
       - "ban %player% %reason%""
      groups:
         default:
          - "bmreload"
   tempban:
      kick: true
      playerserver:
       - "tempban %player% 2d1s %reason%"
      groups:
         default:
          - "bmreload"

patterns:
 - pattern: 'ยง'
   action: ban
   reason: 'Forbidden Client'
   hide: false
   fuzzy: true
 - pattern: '^connected with an .* using MineChat$'
   action: none
   reason: ''
   hide: true
   fuzzy: false
 - pattern: '^I.m chatting on my .* using Minecraft Connect.  Check it out, it.s free ..$'
   action: none
   reason: ''
   hide: true
   fuzzy: false
 - pattern: 'bad word'
   counter: insult
   hide: false
   fuzzy: true