commandsender: "Autoban"

servergroups:
   default:
    - lobby

counters:
   insult:
      max: 4
      ttl: 120
      action: ban
      reason: Insult
   advertising:
      max: 1
      action: tempban
      reason: Advertising
   hack:
      max: 1
      action: ban
      reason: Forbidden Client
   spam:
      deny-repeat: true
      max: 4
      ttl: 10
      rate: 0.5
      action: tempban
      reason: Spam

actions:
   ban:
      kick: true
      playerserver:
       - ban %name% %reason%
      groups:
         default:
          - "bmreload"
   tempban:
      kick: true
      playerserver:
       - tempban %name% 2d1s %reason%
      groups:
         default:
          - "bmreload"

ipcheck:
   counter: advertising
   hide: true
   whitelist:
    - 127.0.0.1
    - 0.0.0.0

patterns:
 - pattern: 'ยง'
   counter: hack
   reason: 'Forbidden Client'
   hide: false
   fuzzy: true
 - pattern: '^connected with an .* using MineChat$'
   hide: true
   fuzzy: false
 - pattern: '^I.m chatting on my .* using Minecraft Connect.  Check it out, it.s free ..$'
   hide: true
   fuzzy: false
 - pattern: 'bad word'
   counter: insult
   hide: false
   fuzzy: true