name: ChannelsAutoban
main: net.zaiyers.ChannelsAutoban.ChannelsAutoban
version: '${minecraft.plugin.version}'
author: zaiyers
depends: [ Channels ]
softDepends: [ BungeeRPC ]
commands:
  channelsautoban:
    aliases: [autoban]
    description: Autoban commands
    usage: '/<command> reload'
    permission: channelsautoban.command
    permission-message: You don't have the permission <permission>
permissions:
  channelsautoban.command:
    description: Command permission
  channelsautoban.command.reload:
    description: Reload command permission